[package]
name = "l4c"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
version = "0.0.0"

[workspace]
members = ['driver']

[dependencies]
getopts = "0.2.11"
log = "0.3.1"
time = "0.1.30"
vec_map = "0.6.0"
bit-vec = "0.4"
fnv = "1.0.0"
env_logger = "0.3"
