[package]
name = "l4c"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
version = "0.0.0"

[profile.release]
debug-assertions = true

[dependencies]
getopts = "0.2.11"
log = "0.3.1"
time = "0.1.30"
libc = "0.1.9"
vec_map = "0.3.0"
bit-vec = "0.4"
fnv = "1.0.0"
env_logger = "0.3"
