use front::ast;

#[deriving(Eq)]
pub enum Token {
  EOF, SEMI, TRUE, FALSE, NULL, ALLOC, ALLOCARR, INT, BOOL, STRUCT, PLUS, MINUS,
  STAR, SLASH, PERCENT, PLUSPLUS, MINUSMINUS, AND, PIPE, BANG, CARET, LSHIFT,
  RSHIFT, TILDE, ANDAND, PIPEPIPE, EQUALS, NEQUALS, ASSIGN, PLUSEQ, MINUSEQ,
  STAREQ, SLASHEQ, PERCENTEQ, XOREQ, ANDEQ, OREQ, LSHIFTEQ, RSHIFTEQ, LESS,
  LESSEQ, GREATER, GREATEREQ, LBRACE, RBRACE, LPAREN, RPAREN, COMMA, PERIOD,
  ARROW, LBRACKET, RBRACKET, IF, ELSE, WHILE, FOR, CONTINUE, BREAK, RETURN,
  TYPEDEF, STATIC, QUESTION, COLON, UNARY, ASNOP, NEWLINE,

  COMMENT(uint),

  INTCONST(i32),
  IDENT(ast::Ident),
  TYPE(ast::Ident),
}
